### ISSUE TITLE
Le package pip est inutilisable.

### ISSUE THREAD

**Issue by mbaudin47** [brunoscherrer/retraites#36]
Le package pip est inutilisable car le fichier json n'est pas installé.

```
$ pip install retraites==0.0.1
Collecting retraites==0.0.1
  Downloading retraites-0.0.1-py3-none-any.whl (38 kB)
[...]
Installing collected packages: retraites
Successfully installed retraites-0.0.1
(testretraitesoff-0.0.1) (base) ~/Documents$ python3
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import retraites
>>> simulateur = retraites.SimulateurRetraites()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/osboxes/Documents/testretraitesoff-0.0.1/lib/python3.7/site-packages/retraites/SimulateurRetraites.py", line 225, in __init__
    json_file = open(json_filename)
FileNotFoundError: [Errno 2] 
No such file or directory: '/home/osboxes/Documents/testretraitesoff-0.0.1/lib/python3.7/site-packages/retraites/fileProjection.json'
```

**Comment by mbaudin47** [comment]
Résolu par #37.
